Fix NoMethodError: undefined method `phone' for nil:NilClass
When trying to add a phone number or job title directly, before adding a
name, the page will crash because the referrer object is nil